### ISSUE TITLE
请问有用法说明吗？

### ISSUE THREAD

**Issue by CairoLee** [ydz/gfw-butter#3]
您好，请问有简单的用法说明吗？

**Comment by yaodong** [comment]
will add

**Comment by yaodong** [comment]
processing

**Comment by CairoLee** [comment]
thank you very much, @yaodong 

now i using routeros 6.3x.
i can use butter -i & butter -g to build the rule file.
But i just don't now how to configure routeros to using them.

**Comment by yaodong** [comment]
@CairoLee 

目前我使用过且运行良好的有两种方法：

## 第一种，转发到 VPN：
- 在 PPP 中添加一个 VPN
- 然后 IP > Routes 中添加规则，将流量转发到 VPN 出口

这种方法操作简单，只需要一个可靠的 VPN 服务即可。这也是目前生成的规则所对应的方案。

但是这种需要一个可靠的 DNS，由于 RouterOS 没有方便的支持 Dnscrypt。而且最近国内的 VPN 的稳定性和速度都不佳。

## 第二种，转发到 HTTP 代理
- 在 IP > Address List 中记录所有的 IP
- 在 NAT 中将这些 IP 转发到内置的 Web Proxy 中
- 在 IP > Web Proxy 中转发到自己的外部 HTTP 代理

这种方法可以使用 Shadowsocks 等代理方式，速度和稳定性都更好一些。但是要求有一个外部 HTTP 代理。

## 接下来要做的
- 使用 IP > Address List 来替代 IP > Routes
- 支持 HTTP Proxy 
- 由于 RouterOS 支持 SSH 登录，所以可以做一个命令来部署上述规则。免去手工配置。
- 然后提供使用 Docker 封装好的的 DNS，HTTP 代理。可以很简单地在国内云服务上一键运行。

上述步骤都会有详细的图文教程。我正在考虑建立一个站点，来将这些东西从一个私用的规则生成器变成一个公用的持久维护的项目。

**Comment by soimy** [comment]
敬候佳音

**Comment by yaodong** [comment]
- 正在制作一个 Web App，可以使用最新数据在线生成各类规则。
- 将会把常用资料发布到 wiki 中。

**Comment by laincat** [comment]
异常期待。。。(会考虑通过 Metarouter 来解决问题么？缺可用 image。。。网上给的偏旧。。。

**Comment by zmzhuai** [comment]
routerOS的web proxy貌似只支持http代理。现在大多网站是HTTPS，无法通过RouterOS的web proxy代理出去吧。好像只能用vpn了 @yaodong

**Comment by yaodong** [comment]
@zmzhuai routerOS 好用的地方就是可以转发到 VPN

**Comment by zmzhuai** [comment]
@yaodong 主要感觉vpn会不会比较不稳定。现在在想有没办法将RouterOS的数据通过dst-nat转到内网架的shadowsocks代理服务器的ss-redir监听的端口。来实现代理。

**Comment by yaodong** [comment]
@zmzhuai 应该可以的。我目前用 RouterOS 将特定 IP 来源的请求转发到局域网内的 Squid 代理上。并没有在用这个 repo 的配置。

**Comment by zmzhuai** [comment]
@yaodong 谢谢回复。刚好周末回去好好试试。有问题后面再请教。

**Comment by zmzhuai** [comment]
@yaodong 昨天试了一下，使用dst-nat会将目的地址换成代理服务器地址，导致ss-redir无法找到原始地址。使用privoxy做中转，只能代理http协议。由于https加密了。也找不到目的地址。请问有什么办法解决吗？

**Comment by yaodong** [comment]
@zmzhuai 抱歉，没试过 ss-redir 和 privoxy。

**Comment by zmzhuai** [comment]
@yaodong 请问你用squid可以支持https的代理吗？用ds-nat，貌似没办法支持加密的代理吧。

**Comment by yaodong** [comment]
@zmzhuai Squid 支持 HTTPS 代理。

**Comment by zmzhuai** [comment]
@yaodong 请问你是用dst-nat中转的吗？如果是https的话。dst-nat的目的地址不是转成代理服务器的ip了吗？代理服务器照理是找不到地址转换前的地址的吧？求赐教

**Comment by yaodong** [comment]
我目前没有用到 dst-net 中转。我目前是在 RouterOS 中设置来源是将特定内网 IP 的流量重定向到 RouterOS 的 cache，然后 cache 的上游是内网的 Squid。但是这个方法不是用来翻墙的，所以可能不能作为翻墙的设置参考。

**Comment by zmzhuai** [comment]
cache 是webproxy吧。我试了，这种方案。只能支持http，如果将443端口的流量定向到RouterOS的cache，一直提示curl: (35) Server aborted the SSL handshake。无法请求。不知你的squid是如何配置的。
@yaodong
